---

- name: Configure neutron controller
  ini_file:
    dest: '/etc/neutron/neutron.conf'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    # Database
    - section: 'database'
      option: 'connection'
      value: '{{ openstack_neutron_controller_neutron_database_url }}'
    # ML2
    - section: 'DEFAULT'
      option: 'core_plugin'
      value: 'ml2'
    - section: 'DEFAULT'
      option: 'service_plugins'
      value: 'router'
    - section: DEFAULT
      option: 'allow_overlapping_ips'
      value: 'True'
    # Messaging
    - section: 'DEFAULT'
      option: 'rpc_backend'
      value: 'rabbit'
    - section: 'oslo_messaging_rabbit'
      option: 'rabbit_host'
      value: '{{ openstack_neutron_controller_rabbit_hostname }}'
    - section: 'oslo_messaging_rabbit'
      option: 'rabbit_userid'
      value: '{{ openstack_neutron_controller_rabbit_username }}'
    - section: 'oslo_messaging_rabbit'
      option: 'rabbit_password'
      value: '{{ openstack_neutron_controller_rabbit_password }}'
    # Keystone
    - section: 'DEFAULT'
      option: 'auth_strategy'
      value: 'keystone'
    - section: keystone_authtoken
      option: identity_uri
      value: >-
        {{- openstack_neutron_controller_keystone_protocol }}://
        {{- openstack_neutron_controller_keystone_hostname }}:
        {{- openstack_neutron_controller_keystone_admin_port }}/
    - section: keystone_authtoken
      option: auth_url
      value: >-
        {{- openstack_neutron_controller_keystone_protocol }}://
        {{- openstack_neutron_controller_keystone_hostname }}:
        {{- openstack_neutron_controller_keystone_admin_port }}/
    - section: keystone_authtoken
      option: auth_uri
      value: >-
        {{- openstack_neutron_controller_keystone_protocol }}://
        {{- openstack_neutron_controller_keystone_hostname }}:
        {{- openstack_neutron_controller_keystone_port }}/v3
    - section: keystone_authtoken
      option: project_domain_name
      value: default
    - section: keystone_authtoken
      option: user_domain_name
      value: default
    - section: keystone_authtoken
      option: memcached_servers
      value: '{{ openstack_neutron_controller_keystone_hostname }}:11211'
    - section: keystone_authtoken
      option: project_name
      value: service
    - section: keystone_authtoken
      option: auth_type
      value: password
    - section: keystone_authtoken
      option: auth_version
      value: v3
    - section: keystone_authtoken
      option: username
      value: '{{ openstack_neutron_controller_neutron_user }}'
    - section: keystone_authtoken
      option: password
      value: '{{ openstack_neutron_controller_neutron_password }}'
    # Nova
    - section: 'nova'
      option: 'auth_url'
      value: >-
        {{- openstack_neutron_controller_keystone_protocol }}://
        {{- openstack_neutron_controller_keystone_hostname }}:
        {{- openstack_neutron_controller_keystone_admin_port }}/
    - section: nova
      option: project_domain_name
      value: default
    - section: nova
      option: user_domain_name
      value: default
    - section: nova
      option: project_name
      value: service
    - section: nova
      option: auth_type
      value: password
    - section: nova
      option: project_name
      value: service
    - section: nova
      option: username
      value: '{{ openstack_neutron_controller_nova_username }}'
    - section: nova
      option: password
      value: '{{ openstack_neutron_controller_nova_password }}'
  notify:
    - Sync neutron database
    - Restart neutron server

# FIXME: Enable services for RH

- name: Link default neutron plugin
  file:
    src: '/etc/neutron/plugins/ml2/ml2_conf.ini'
    dest: '/etc/neutron/plugin.ini'
    owner: neutron
    state: link
  when: ansible_os_family == 'RedHat'

- name: Configure the Modular Layer 2 plugin
  ini_file:
    dest: '/etc/neutron/plugins/ml2/ml2_conf.ini'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - section: 'ml2'
      option: 'type_drivers'
      value: 'flat,vlan,vxlan'
    - section: 'ml2'
      option: 'tenant_network_types'
      value: 'vxlan'
    - section: 'ml2'
      option: 'mechanism_drivers'
      value: 'linuxbridge,l2population'
    - section: 'ml2'
      option: 'extension_drivers'
      value: 'port_security'
    - section: 'ml2_type_flat'
      option: 'flat_networks'
      value: 'provider'
    - section: 'ml2_type_vxlan'
      option: 'vni_ranges'
      value: '1:1000'
    - section: 'securitygroup'
      option: 'enable_ipset'
      value: 'True'
  notify:
    - Sync neutron database
    - Restart neutron server

- name: Configure the Linux Bridge agent
  ini_file:
    dest: '/etc/neutron/plugins/ml2/linuxbridge_agent.ini'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - section: 'linux_bridge'
      option: 'physical_interface_mappings'
      value: 'provider:{{ openstack_neutron_controller_provider_interface_name }}'  # name of the underlying provider physical network interface (to Internet)
    - section: 'vxlan'
      option: 'enable_vxlan'
      value: 'True'
    - section: 'vxlan'
      option: 'local_ip'
      value: '{{ openstack_neutron_controller_overlay_interface_address }}'  # MGMT interface
    - section: 'vxlan'
      option: 'l2_population'
      value: 'True'
    - section: 'securitygroup'
      option: 'enable_security_group'
      value: 'True'
    - section: 'securitygroup'
      option: 'firewall_driver'
      value: 'neutron.agent.linux.iptables_firewall.IptablesFirewallDriver'
  notify:
    - Restart linuxbridge agent

- name: Configure the Layer-3 agent
  ini_file:
    dest: '/etc/neutron/l3_agent.ini'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - section: 'DEFAULT'
      option: 'interface_driver'
      value: 'neutron.agent.linux.interface.BridgeInterfaceDriver'
    - section: 'DEFAULT'
      option: 'external_network_bridge'
      value: ''
  notify:
    - Restart neutron L3 agent

- name: Configure the DHCP agent
  ini_file:
    dest: '/etc/neutron/dhcp_agent.ini'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - section: 'DEFAULT'
      option: 'interface_driver'
      value: 'neutron.agent.linux.interface.BridgeInterfaceDriver'
    - section: 'DEFAULT'
      option: 'dhcp_driver'
      value: 'neutron.agent.linux.dhcp.Dnsmasq'
    - section: 'DEFAULT'
      option: 'enable_isolated_metadata'
      value: 'True'
  notify:
    - Restart DHCP agent

- name: Configure the metadata agent
  ini_file:
    dest: '/etc/neutron/metadata_agent.ini'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - section: 'DEFAULT'
      option: 'nova_metadata_ip'
      value: '{{ openstack_neutron_controller_neutron_nova_metadata_ip }}'
    - section: 'DEFAULT'
      option: 'metadata_proxy_shared_secret'
      value: '{{ openstack_neutron_controller_neutron_metadata_secret }}'
  notify:
    - Restart metadata agent
